In [1]:
import game1

In [2]:
import json
with open('./data/spoc/scheduling/candidates.txt') as f:
    data = json.load(f)
import numpy as np
# 规约为一个简单点的表示
# List of Opportunity,
# Opportunity = [time, station, asteroid, A, B, C] .
opportunities = []
for asteroid in data.keys():
    for station in data[asteroid].keys():
        for op in data[asteroid][station]:
            # print(op)
            opportunities.append([op[0], int(station), int(asteroid), *op[1:]])
opportunities.sort(key=lambda x: x[0])
opportunities = np.array(opportunities)

In [3]:
g = game1.WaterDropMarch(opportunities)
s = g.state
# s['current_op'] = 0
# s['current_row'] = 0
# s['disabled'] = np.zeros(len(opportunities))
s

Dict(currentABC:Box([0. 0. 0.], [inf inf inf], (3,), float32), current_op:Discrete(13920), current_row:Discrete(13), disabled:MultiBinary(13920))
OrderedDict([('currentABC', 0), ('current_op', 0), ('current_row', 0), ('disabled', 0)])


OrderedDict([('currentABC', 0),
             ('current_op', 0),
             ('current_row', 0),
             ('disabled', 0)])

In [33]:
s = g.observation_space.sample()
s

OrderedDict([('currentABC',
              array([0.54416406, 1.554267  , 1.0078822 ], dtype=float32)),
             ('current_op', 1606),
             ('current_row', 9),
             ('disabled', array([0, 1, 0, ..., 1, 1, 0], dtype=int8))])

In [34]:
s['disabled']*=0
s

OrderedDict([('currentABC',
              array([0.54416406, 1.554267  , 1.0078822 ], dtype=float32)),
             ('current_op', 1606),
             ('current_row', 9),
             ('disabled', array([0, 0, 0, ..., 0, 0, 0], dtype=int8))])

In [28]:
a = {1:np.ones(5)}
t = a[1]
t = 0
t

0

In [32]:
a = np.ones(10)
# a = 0
a *= 0
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
g.observation_space.keys()
g.observation_space['currentABC']

Box([0. 0. 0.], [inf inf inf], (3,), float32)