In [15]:
import numpy as np
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
B = np.zeros((3, 6))
B[:, 1::2] = A
B

array([[0., 0., 0., 1., 0., 2.],
       [0., 3., 0., 4., 0., 5.],
       [0., 6., 0., 7., 0., 8.]])

In [22]:
C= np.arange(10)
np.tile(C,(5, 1))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [25]:
C[0::2]

array([0, 2, 4, 6, 8])

In [27]:
[a for a in A]

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [28]:
a = [0,1,2]
a[:3]

[0, 1, 2]